Repository djunicode/canteen-automation-web, pull requests merged in 2019-01, with the labels that each got.

#43 Add HTTP endpoints for completed/ pending orders and order status change
  canteenWeb/choices.py
  canteenWeb/serializers.py
  canteenWeb/views.py
Labels: backend, in progress

#46 Resolved Conflicts and Modified Models
  canteenAutomation/urls.py
  canteenWeb/admin.py
  canteenWeb/choices.py
  canteenWeb/forms.py
  canteenWeb/models.py
  canteenWeb/serializers.py
  canteenWeb/tests.py
  canteenWeb/urls.py
  canteenWeb/views.py
Labels: in progress

#48 Add Django Channels
  canteenAutomation/asgi.py
  canteenAutomation/routing.py
  canteenAutomation/settings.py
  canteenAutomation/wsgi.py
  canteenWeb/__init__.py
  canteenWeb/apps.py
  canteenWeb/consumers.py
  canteenWeb/routing.py
  canteenWeb/serializers.py
  canteenWeb/signals.py
  canteenWeb/tests.py
  canteenWeb/urls.py
  canteenWeb/views.py
  manage.py
  requirements.txt
Labels: backend
